/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2026-06-21 04:38:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html class=\"light\" lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n");
      out.write("    <title>OlwShare - Login</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Manrope:wght@700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com?plugins=forms,container-queries\"></script>\n");
      out.write("    <script>\n");
      out.write("        tailwind.config = {\n");
      out.write("            theme: { extend: { colors: {\n");
      out.write("                \"surface\": \"#f7f9fc\", \"surface-container\": \"#eceef1\",\n");
      out.write("                \"surface-container-low\": \"#f2f4f7\", \"surface-container-highest\": \"#e0e3e6\",\n");
      out.write("                \"surface-container-lowest\": \"#ffffff\", \"on-surface\": \"#191c1e\",\n");
      out.write("                \"on-surface-variant\": \"#454652\", \"primary\": \"#24389c\",\n");
      out.write("                \"primary-container\": \"#3f51b5\", \"on-primary\": \"#ffffff\",\n");
      out.write("                \"secondary\": \"#006a60\", \"outline\": \"#757684\", \"outline-variant\": \"#c5c5d4\"\n");
      out.write("            }}}\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    <style>\n");
      out.write("        .material-symbols-outlined {\n");
      out.write("            font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24;\n");
      out.write("            vertical-align: middle;\n");
      out.write("        }\n");
      out.write("        body { font-family: 'Inter', sans-serif; }\n");
      out.write("        h1, h2, h3 { font-family: 'Manrope', sans-serif; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-surface text-on-surface min-h-screen flex flex-col\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<header class=\"bg-white/80 backdrop-blur-xl sticky top-0 z-50 shadow-[0_20px_40px_rgba(25,28,30,0.08)]\">\n");
      out.write("    <div class=\"flex justify-between items-center w-full px-8 py-4 max-w-screen-2xl mx-auto\">\n");
      out.write("        <span class=\"text-2xl font-extrabold text-indigo-900 tracking-tighter\"\n");
      out.write("              style=\"font-family:'Manrope',sans-serif\">OlwShare</span>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<main class=\"flex-grow flex items-center justify-center px-6 py-12\">\n");
      out.write("    <div class=\"w-full max-w-md\">\n");
      out.write("        <div class=\"bg-surface-container-lowest rounded-xl shadow-[0_20px_40px_rgba(25,28,30,0.08)] overflow-hidden\">\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div class=\"bg-surface-container-low p-8 text-center\">\n");
      out.write("                <h2 class=\"text-3xl font-extrabold text-primary tracking-tight mb-2\">Bienvenido</h2>\n");
      out.write("                <p class=\"text-on-surface-variant text-sm font-medium\">Panel de Administración · OlwShare</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"p-8 space-y-6\">\n");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("                ");
 if (request.getParameter("mensaje") != null) { 
      out.write("\n");
      out.write("                <div class=\"flex items-center gap-3 bg-green-50 text-green-700 text-sm font-medium px-4 py-3 rounded-lg border border-green-100\">\n");
      out.write("                    <span class=\"material-symbols-outlined text-base\">check_circle</span>\n");
      out.write("                    ");
      out.print( request.getParameter("mensaje") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("                ");
 if (request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("                <div class=\"flex items-center gap-3 bg-red-50 text-red-700 text-sm font-medium px-4 py-3 rounded-lg\">\n");
      out.write("                    <span class=\"material-symbols-outlined text-base\">error</span>\n");
      out.write("                    ");
      out.print( request.getAttribute("error") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"post\" class=\"space-y-5\">\n");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    <div class=\"space-y-1.5\">\n");
      out.write("                        <label class=\"text-xs font-semibold text-primary uppercase tracking-wider ml-1\" for=\"email\">\n");
      out.write("                            Email\n");
      out.write("                        </label>\n");
      out.write("                        <div class=\"relative\">\n");
      out.write("                            <div class=\"absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none\">\n");
      out.write("                                <span class=\"material-symbols-outlined text-outline text-sm\">mail</span>\n");
      out.write("                            </div>\n");
      out.write("                            <input class=\"block w-full pl-10 pr-4 py-3 bg-surface-container-highest border-none rounded-lg\n");
      out.write("                                          focus:ring-2 focus:ring-indigo-300 text-on-surface placeholder:text-outline/60\n");
      out.write("                                          outline-none transition-all\"\n");
      out.write("                                   id=\"email\" name=\"email\" type=\"email\"\n");
      out.write("                                   placeholder=\"admin@olwshare.com\"\n");
      out.write("                                   value=\"");
      out.print( request.getParameter("email") != null ? request.getParameter("email") : "" );
      out.write("\"\n");
      out.write("                                   required/>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    <div class=\"space-y-1.5\">\n");
      out.write("                        <label class=\"text-xs font-semibold text-primary uppercase tracking-wider\" for=\"password\">\n");
      out.write("                            Contraseña\n");
      out.write("                        </label>\n");
      out.write("                        <div class=\"relative\">\n");
      out.write("                            <div class=\"absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none\">\n");
      out.write("                                <span class=\"material-symbols-outlined text-outline text-sm\">lock</span>\n");
      out.write("                            </div>\n");
      out.write("                            <input class=\"block w-full pl-10 pr-4 py-3 bg-surface-container-highest border-none rounded-lg\n");
      out.write("                                          focus:ring-2 focus:ring-indigo-300 text-on-surface placeholder:text-outline/60\n");
      out.write("                                          outline-none transition-all\"\n");
      out.write("                                   id=\"password\" name=\"password\" type=\"password\"\n");
      out.write("                                   placeholder=\"••••••••\" required/>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    <button type=\"submit\"\n");
      out.write("                            class=\"w-full py-4 bg-gradient-to-br from-primary to-primary-container text-on-primary\n");
      out.write("                                   font-bold rounded-lg shadow-md hover:opacity-90 active:scale-[0.98] transition-all\n");
      out.write("                                   flex justify-center items-center gap-2\"\n");
      out.write("                            style=\"font-family:'Manrope',sans-serif\">\n");
      out.write("                        <span>Entrar</span>\n");
      out.write("                        <span class=\"material-symbols-outlined\">arrow_forward</span>\n");
      out.write("                    </button>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("                <div class=\"text-center pt-2\">\n");
      out.write("                    <p class=\"text-sm text-slate-500\">\n");
      out.write("                        ¿No tienes una cuenta?\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/registro\" class=\"text-primary font-bold hover:underline\">Regístrate aquí</a>\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div class=\"bg-surface-container h-1 w-full overflow-hidden\">\n");
      out.write("                <div class=\"bg-secondary h-full w-1/3\"></div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"mt-8 grid grid-cols-2 gap-4\">\n");
      out.write("            <div class=\"bg-surface-container-low p-4 rounded-lg flex items-center gap-3\">\n");
      out.write("                <div class=\"bg-white p-2 rounded-full shadow-sm\">\n");
      out.write("                    <span class=\"material-symbols-outlined text-secondary\">verified</span>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <p class=\"text-[10px] font-bold text-on-surface-variant uppercase tracking-tighter\">Material</p>\n");
      out.write("                    <p class=\"text-xs font-bold text-on-surface\">Curated Quality</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"bg-surface-container-low p-4 rounded-lg flex items-center gap-3\">\n");
      out.write("                <div class=\"bg-white p-2 rounded-full shadow-sm\">\n");
      out.write("                    <span class=\"material-symbols-outlined text-primary\">groups</span>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <p class=\"text-[10px] font-bold text-on-surface-variant uppercase tracking-tighter\">Community</p>\n");
      out.write("                    <p class=\"text-xs font-bold text-on-surface\">Study Groups</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"w-full py-8 mt-auto border-t border-slate-100 bg-slate-50\">\n");
      out.write("    <div class=\"text-center\">\n");
      out.write("        <span class=\"text-xs text-slate-400\">© 2025 OlwShare. Todos los derechos reservados.</span>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"fixed top-0 right-0 -z-10 w-1/3 h-full overflow-hidden pointer-events-none opacity-40\">\n");
      out.write("    <div class=\"absolute top-[-10%] right-[-10%] w-[500px] h-[500px] bg-indigo-500/5 rounded-full blur-[100px]\"></div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
