/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2026-06-21 04:42:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class registro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/nesda/Desktop/EPN/Metodolgías%20Ágiles/OwlShare/target/owlshare-1.0-SNAPSHOT/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664471478000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1776646240090L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n");
      out.write("    <title>Registro - OlwShare</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Manrope:wght@400;600;700;800&family=Inter:wght@400;500;600&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com?plugins=forms,container-queries\"></script>\n");
      out.write("    <script>\n");
      out.write("        tailwind.config = {\n");
      out.write("            theme: { extend: { colors: {\n");
      out.write("                \"primary\": \"#24389c\", \"primary-container\": \"#3f51b5\", \"on-primary\": \"#ffffff\",\n");
      out.write("                \"surface\": \"#f7f9fc\", \"on-surface\": \"#191c1e\", \"error\": \"#ba1a1a\"\n");
      out.write("            }}}\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: 'Inter', sans-serif; }\n");
      out.write("        h1, h2 { font-family: 'Manrope', sans-serif; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-surface text-on-surface min-h-screen flex items-center justify-center p-4\">\n");
      out.write("\n");
      out.write("<div class=\"max-w-2xl w-full bg-white rounded-2xl shadow-xl p-8 md:p-12\">\n");
      out.write("    <div class=\"text-center mb-10\">\n");
      out.write("        <div class=\"inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-indigo-50 text-primary mb-4\">\n");
      out.write("            <span class=\"material-symbols-outlined text-4xl\">person_add</span>\n");
      out.write("        </div>\n");
      out.write("        <h1 class=\"text-3xl font-extrabold text-indigo-900 tracking-tight\">Crea tu cuenta</h1>\n");
      out.write("        <p class=\"text-slate-500 mt-2\">Únete a la comunidad de OlwShare</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/registro\" method=\"POST\" class=\"space-y-6\">\n");
      out.write("        <div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\">\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div class=\"md:col-span-2\">\n");
      out.write("                <label class=\"block text-sm font-bold text-indigo-900 mb-2\">Correo Electrónico *</label>\n");
      out.write("                <input type=\"email\" name=\"email\" required\n");
      out.write("                       class=\"w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring focus:ring-indigo-200 transition-all text-sm outline-none p-3 border\"\n");
      out.write("                       placeholder=\"ejemplo@correo.com\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div class=\"md:col-span-2\">\n");
      out.write("                <label class=\"block text-sm font-bold text-indigo-900 mb-2\">Contraseña *</label>\n");
      out.write("                <input type=\"password\" name=\"password\" required\n");
      out.write("                       class=\"w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring focus:ring-indigo-200 transition-all text-sm outline-none p-3 border\"\n");
      out.write("                       placeholder=\"••••••••\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <label class=\"block text-sm font-bold text-indigo-900 mb-2\">Primer Nombre *</label>\n");
      out.write("                <input type=\"text\" name=\"nombre\" required\n");
      out.write("                       class=\"w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring focus:ring-indigo-200 transition-all text-sm outline-none p-3 border\"\n");
      out.write("                       placeholder=\"Nombre\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <label class=\"block text-sm font-bold text-indigo-900 mb-2\">Segundo Nombre</label>\n");
      out.write("                <input type=\"text\" name=\"segundoNombre\"\n");
      out.write("                       class=\"w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring focus:ring-indigo-200 transition-all text-sm outline-none p-3 border\"\n");
      out.write("                       placeholder=\"Segundo Nombre\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <label class=\"block text-sm font-bold text-indigo-900 mb-2\">Primer Apellido *</label>\n");
      out.write("                <input type=\"text\" name=\"apellido\" required\n");
      out.write("                       class=\"w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring focus:ring-indigo-200 transition-all text-sm outline-none p-3 border\"\n");
      out.write("                       placeholder=\"Apellido\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <label class=\"block text-sm font-bold text-indigo-900 mb-2\">Segundo Apellido</label>\n");
      out.write("                <input type=\"text\" name=\"segundoApellido\"\n");
      out.write("                       class=\"w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring focus:ring-indigo-200 transition-all text-sm outline-none p-3 border\"\n");
      out.write("                       placeholder=\"Segundo Apellido\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <label class=\"block text-sm font-bold text-indigo-900 mb-2\">\n");
      out.write("                    Semestre <span id=\"semestreLabelExtra\" class=\"text-slate-400 font-normal text-xs\"></span>\n");
      out.write("                </label>\n");
      out.write("                <select id=\"selectSemestreRegistro\" name=\"semestre\"\n");
      out.write("                        class=\"w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring focus:ring-indigo-200 transition-all text-sm outline-none p-3 border\">\n");
      out.write("                    <option value=\"\">-- Selecciona tu semestre --</option>\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </select>\n");
      out.write("                <p id=\"hintSemestreTutor\" class=\"hidden text-xs text-slate-500 mt-1\">\n");
      out.write("                    Solo podrás elegir materias de semestres <strong>anteriores</strong> al que cursas (ej. 5.º → 1.º a 4.º).\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <label class=\"block text-sm font-bold text-indigo-900 mb-2\">\n");
      out.write("                    Carrera <span id=\"carreraLabelExtra\" class=\"text-slate-400 font-normal text-xs\"></span>\n");
      out.write("                </label>\n");
      out.write("                <select id=\"selectCarreraRegistro\" name=\"carrera\"\n");
      out.write("                        class=\"w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring focus:ring-indigo-200 transition-all text-sm outline-none p-3 border\">\n");
      out.write("                    <option value=\"\">-- Selecciona tu carrera --</option>\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div class=\"md:col-span-2\">\n");
      out.write("                <label class=\"block text-sm font-bold text-indigo-900 mb-2\">Rol deseado *</label>\n");
      out.write("                <select id=\"rolSelect\" name=\"rol\" required\n");
      out.write("                        class=\"w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring focus:ring-indigo-200 transition-all text-sm outline-none p-3 border\">\n");
      out.write("                    <option value=\"\" disabled selected>Selecciona un rol</option>\n");
      out.write("                    <option value=\"ESTUDIANTE\">Estudiante</option>\n");
      out.write("                    <option value=\"TUTOR\">Tutor</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div id=\"seccionMaterias\" class=\"hidden space-y-4\">\n");
      out.write("            <div>\n");
      out.write("                <label class=\"block text-sm font-bold text-indigo-900 mb-2\">Materias relacionadas *</label>\n");
      out.write("                <p class=\"text-xs text-slate-500 mb-2\">Misma <strong>carrera</strong> y <strong>semestre</strong> que arriba: solo asignaturas de semestres ya cursados (inferiores al tuyo).</p>\n");
      out.write("                <div id=\"chipsRegistro\" class=\"flex flex-wrap gap-2 mb-3 min-h-[2rem]\"></div>\n");
      out.write("                <select id=\"selectMateriaRegistro\" disabled\n");
      out.write("                        class=\"w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring focus:ring-indigo-200 transition-all text-sm outline-none p-3 border\">\n");
      out.write("                    <option value=\"\">— Primero confirma tu carrera arriba —</option>\n");
      out.write("                </select>\n");
      out.write("                <p id=\"errorMaterias\" class=\"hidden mt-2 text-sm text-red-600 font-medium flex items-center gap-1\">\n");
      out.write("                    <span class=\"material-symbols-outlined text-base\">error</span>\n");
      out.write("                    <span id=\"errorMateriasMsg\">Debes seleccionar al menos una materia.</span>\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <button type=\"submit\" id=\"btnRegistro\"\n");
      out.write("                class=\"w-full bg-primary text-white font-bold py-3.5 rounded-xl hover:bg-primary-container transition-all shadow-lg shadow-indigo-200 mt-4\">\n");
      out.write("            Registrarse\n");
      out.write("        </button>\n");
      out.write("\n");
      out.write("        <p class=\"text-center text-sm text-slate-500\">\n");
      out.write("            ¿Ya tienes una cuenta?\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"text-primary font-bold hover:underline\">Inicia sesión</a>\n");
      out.write("        </p>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script type=\"application/json\" id=\"materiasPorCarreraJsonReg\">");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    (function () {\n");
      out.write("        var rolSelect        = document.getElementById('rolSelect');\n");
      out.write("        var seccionMaterias  = document.getElementById('seccionMaterias');\n");
      out.write("        var selectCarrera    = document.getElementById('selectCarreraRegistro');\n");
      out.write("        var selectSemestre   = document.getElementById('selectSemestreRegistro');\n");
      out.write("        var selectMateria    = document.getElementById('selectMateriaRegistro');\n");
      out.write("        var chipsContainer   = document.getElementById('chipsRegistro');\n");
      out.write("        var errorMaterias    = document.getElementById('errorMaterias');\n");
      out.write("        var form             = document.querySelector('form');\n");
      out.write("        var materiasPorCarrera = JSON.parse(document.getElementById('materiasPorCarreraJsonReg').textContent);\n");
      out.write("\n");
      out.write("        var selectedCodigos = new Set();\n");
      out.write("\n");
      out.write("        function topeSemestreTutor() {\n");
      out.write("            if (rolSelect.value !== 'TUTOR') return null;\n");
      out.write("            var opt = selectSemestre.options[selectSemestre.selectedIndex];\n");
      out.write("            if (!opt || !opt.value) return null;\n");
      out.write("            var n = parseInt(opt.getAttribute('data-num'), 10);\n");
      out.write("            return isNaN(n) ? null : n;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function appendHintOption(text) {\n");
      out.write("            var h = document.createElement('option');\n");
      out.write("            h.value = '';\n");
      out.write("            h.disabled = true;\n");
      out.write("            h.textContent = text;\n");
      out.write("            selectMateria.appendChild(h);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function refillMaterias() {\n");
      out.write("            selectMateria.innerHTML = '';\n");
      out.write("            var def = document.createElement('option');\n");
      out.write("            def.value = '';\n");
      out.write("            def.textContent = '— Seleccionar materia —';\n");
      out.write("            selectMateria.appendChild(def);\n");
      out.write("\n");
      out.write("            if (rolSelect.value !== 'TUTOR') {\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            var car = selectCarrera.value;\n");
      out.write("            if (!car || !materiasPorCarrera[car]) {\n");
      out.write("                appendHintOption('— Primero elige tu carrera arriba —');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            var tope = topeSemestreTutor();\n");
      out.write("            if (tope == null) {\n");
      out.write("                appendHintOption('— Primero elige tu semestre arriba —');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            if (tope <= 1) {\n");
      out.write("                appendHintOption('— En 1.er semestre no puedes ofrecer materias —');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            var list = materiasPorCarrera[car].slice().filter(function (m) {\n");
      out.write("                return m.semestre < tope;\n");
      out.write("            }).sort(function (a, b) {\n");
      out.write("                if (a.semestre !== b.semestre) return a.semestre - b.semestre;\n");
      out.write("                return a.nombre.localeCompare(b.nombre);\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            if (list.length === 0) {\n");
      out.write("                appendHintOption('— No hay materias de semestres anteriores para tu caso —');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            list.forEach(function (m) {\n");
      out.write("                var opt = document.createElement('option');\n");
      out.write("                opt.value = m.codigo;\n");
      out.write("                opt.setAttribute('data-nombre', m.nombre);\n");
      out.write("                opt.textContent = m.nombre + ' — ' + m.codigo;\n");
      out.write("                selectMateria.appendChild(opt);\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function clearMaterias() {\n");
      out.write("            selectedCodigos.forEach(function (cod) {\n");
      out.write("                var h = document.getElementById('hidden_mat_' + cod.replace(/[^a-zA-Z0-9]/g, '_'));\n");
      out.write("                if (h) h.remove();\n");
      out.write("            });\n");
      out.write("            selectedCodigos.clear();\n");
      out.write("            chipsContainer.innerHTML = '';\n");
      out.write("            errorMaterias.classList.add('hidden');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function syncRolUi() {\n");
      out.write("            var hint = document.getElementById('hintSemestreTutor');\n");
      out.write("            var extraSemestre = document.getElementById('semestreLabelExtra');\n");
      out.write("            var extraCarrera = document.getElementById('carreraLabelExtra');\n");
      out.write("            var esTutor = rolSelect.value === 'TUTOR';\n");
      out.write("\n");
      out.write("            extraSemestre.textContent = esTutor ? '(obligatorio)' : '';\n");
      out.write("            extraCarrera.textContent = esTutor ? '(obligatorio)' : '';\n");
      out.write("            hint.classList.toggle('hidden', !esTutor);\n");
      out.write("\n");
      out.write("            // Campos exclusivos de tutor: requeridos y habilitados solo si el rol es TUTOR;\n");
      out.write("            // deshabilitados cuando el rol no es TUTOR para que no se envíen con el formulario.\n");
      out.write("            selectSemestre.required = esTutor;\n");
      out.write("            selectCarrera.required = esTutor;\n");
      out.write("            selectMateria.disabled = !esTutor;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        rolSelect.addEventListener('change', function () {\n");
      out.write("            if (this.value === 'TUTOR') {\n");
      out.write("                seccionMaterias.classList.remove('hidden');\n");
      out.write("                syncRolUi();\n");
      out.write("                refillMaterias();\n");
      out.write("            } else {\n");
      out.write("                seccionMaterias.classList.add('hidden');\n");
      out.write("                clearMaterias();\n");
      out.write("                syncRolUi();\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        selectSemestre.addEventListener('change', function () {\n");
      out.write("            if (rolSelect.value === 'TUTOR') {\n");
      out.write("                clearMaterias();\n");
      out.write("                refillMaterias();\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        selectCarrera.addEventListener('change', function () {\n");
      out.write("            if (rolSelect.value === 'TUTOR') {\n");
      out.write("                clearMaterias();\n");
      out.write("                refillMaterias();\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        selectMateria.addEventListener('change', function () {\n");
      out.write("            var opt = this.options[this.selectedIndex];\n");
      out.write("            var cod = opt.value;\n");
      out.write("            var nombre = opt.getAttribute('data-nombre');\n");
      out.write("            this.value = '';\n");
      out.write("            if (!cod || selectedCodigos.has(cod)) return;\n");
      out.write("            selectedCodigos.add(cod);\n");
      out.write("            errorMaterias.classList.add('hidden');\n");
      out.write("\n");
      out.write("            var chip = document.createElement('span');\n");
      out.write("            chip.className = 'inline-flex items-center gap-1 px-3 py-1 rounded-full text-sm font-semibold text-white';\n");
      out.write("            chip.style.backgroundColor = '#56C7E6';\n");
      out.write("\n");
      out.write("            var hidden = document.createElement('input');\n");
      out.write("            hidden.type = 'hidden';\n");
      out.write("            hidden.name = 'materias';\n");
      out.write("            hidden.value = cod;\n");
      out.write("            hidden.id = 'hidden_mat_' + cod.replace(/[^a-zA-Z0-9]/g, '_');\n");
      out.write("\n");
      out.write("            var label = document.createElement('span');\n");
      out.write("            label.textContent = nombre || cod;\n");
      out.write("\n");
      out.write("            var btn = document.createElement('button');\n");
      out.write("            btn.type = 'button';\n");
      out.write("            btn.className = 'ml-1 text-white/80 hover:text-white font-bold leading-none';\n");
      out.write("            btn.textContent = '×';\n");
      out.write("            btn.addEventListener('click', function () {\n");
      out.write("                selectedCodigos.delete(cod);\n");
      out.write("                chip.remove();\n");
      out.write("                var h = document.getElementById('hidden_mat_' + cod.replace(/[^a-zA-Z0-9]/g, '_'));\n");
      out.write("                if (h) h.remove();\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            chip.appendChild(label);\n");
      out.write("            chip.appendChild(btn);\n");
      out.write("            chipsContainer.appendChild(chip);\n");
      out.write("            form.appendChild(hidden);\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        form.addEventListener('submit', function (e) {\n");
      out.write("            if (rolSelect.value === 'TUTOR') {\n");
      out.write("                if (!selectSemestre.value) {\n");
      out.write("                    e.preventDefault();\n");
      out.write("                    document.getElementById('errorMateriasMsg').textContent = 'Selecciona tu semestre.';\n");
      out.write("                    errorMaterias.classList.remove('hidden');\n");
      out.write("                    selectSemestre.focus();\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                var tn = topeSemestreTutor();\n");
      out.write("                if (tn !== null && tn <= 1) {\n");
      out.write("                    e.preventDefault();\n");
      out.write("                    document.getElementById('errorMateriasMsg').textContent =\n");
      out.write("                        'En primer semestre no puedes ofrecer materias como tutor; elige otro semestre o regístrate como estudiante.';\n");
      out.write("                    errorMaterias.classList.remove('hidden');\n");
      out.write("                    selectSemestre.focus();\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                if (!selectCarrera.value) {\n");
      out.write("                    e.preventDefault();\n");
      out.write("                    document.getElementById('errorMateriasMsg').textContent = 'Selecciona tu carrera.';\n");
      out.write("                    errorMaterias.classList.remove('hidden');\n");
      out.write("                    selectCarrera.focus();\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                if (selectedCodigos.size === 0) {\n");
      out.write("                    e.preventDefault();\n");
      out.write("                    document.getElementById('errorMateriasMsg').textContent = 'Debes seleccionar al menos una materia.';\n");
      out.write("                    errorMaterias.classList.remove('hidden');\n");
      out.write("                    seccionMaterias.scrollIntoView({ behavior: 'smooth', block: 'center' });\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    })();\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /registro.jsp(36,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <div class=\"mb-6 flex items-center gap-3 bg-red-50 text-red-700 text-sm font-medium px-4 py-3 rounded-lg border border-red-100\">\n");
          out.write("            <span class=\"material-symbols-outlined text-base\">error</span>\n");
          out.write("            ");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("        </div>\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /registro.jsp(39,12) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /registro.jsp(101,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("sem");
      // /registro.jsp(101,20) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/registro.jsp(101,20) '${semestres}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${semestres}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                        <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sem.name()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-num=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sem.numero}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</option>\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /registro.jsp(102,79) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sem.nombre}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /registro.jsp(118,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("car");
      // /registro.jsp(118,20) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/registro.jsp(118,20) '${carreras}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${carreras}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                        <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${car.name()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</option>\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /registro.jsp(119,54) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${car.nombre}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /registro.jsp(165,63) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materiasPorCarreraJson}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /registro.jsp(165,63) name = escapeXml type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setEscapeXml(false);
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }
}
